apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus.yaml
  - alertmanager.yaml
  - node-exporter.yaml
  - grafana.yaml
  - loki.yaml
  - promtail.yaml
  - tempo.yaml
  - otel-collector.yaml
  - network-policies.yaml
