apiVersion: 1
providers:
  - name: Platform Operations
    orgId: 1
    type: file
    disableDeletion: true
    allowUiUpdates: false
    updateIntervalSeconds: 30
    options:
      path: /var/lib/grafana/provisioned
      foldersFromFilesStructure: false
