apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - namespace.yaml
namespace: __PROJECT_SLUG__
images:
  - name: registry.dev.home.arpa/__PROJECT_SLUG__
    newName: registry.dev.home.arpa/__PROJECT_SLUG__
    newTag: latest
