apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: addon-acceptance-egress
spec:
  podSelector:
    matchLabels:
      platform.dev.home.arpa/addon-client: "true"
  policyTypes: [Egress]
  egress:
    - to:
        - podSelector: {}
      ports:
        - {protocol: TCP, port: 10000}
        - {protocol: TCP, port: 10001}
        - {protocol: TCP, port: 10002}
    - to:
        - podSelector: {}
      ports:
        - {protocol: TCP, port: 4443}
    - to:
        - podSelector: {}
      ports:
        - {protocol: TCP, port: 4566}
