apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloud-emulators
resources:
  - acceptance-network-policy.yaml
  - azurite
  - fake-gcs
labels:
  - pairs:
      app.kubernetes.io/part-of: optional-development-services
      app.kubernetes.io/managed-by: kustomize
