{
 "title": "Traces Overview",
 "tags": [
  "local-observability",
  "traces"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "service", "label": "Service", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Trace Search By Service",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "limit": 20,
     "query": "{ resource.service.name =~ \"$service\" }"
    }
   ]
  },
  {
   "title": "Slow Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "limit": 20,
     "query": "{ resource.service.name =~ \"$service\" && duration > 250ms }"
    }
   ]
  },
  {
   "title": "Failed Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "limit": 20,
     "query": "{ resource.service.name =~ \"$service\" && status = error }"
    }
   ]
  }
 ]
}