services:
  fake-gcs-server:
    image: fsouza/fake-gcs-server:1.52.3
    command:
      - -scheme
      - http
      - -host
      - 0.0.0.0
      - -port
      - "4443"
      - -data
      - /data
    ports:
      - "4443:4443"
    volumes:
      - ./seed:/data
